version: '3.7'

services:
  uh:
    container_name: uh_container
    build:
      context: ./
      dockerfile: Dockerfile
    image: uh
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "80:80"
    networks:
      - uh
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped

  db:
    image: postgres
    environment:
      POSTGRES_DB: uh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5430:5432"
    networks:
      - uh
    restart: unless-stopped

networks:
  uh: {}

volumes:
  postgres: